var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/dashboard/orders/[id]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0pd7lcy._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0~4.pri.js")
R.c("server/chunks/ssr/[root-of-the-server]__0eh9ux8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_06hehg4._.js")
R.c("server/chunks/ssr/_0jytjc.._.js")
R.c("server/chunks/ssr/_0on~~aa._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/app_dashboard_layout_jsx_03b1o_c._.js")
R.c("server/chunks/ssr/_next-internal_server_app_dashboard_orders_[id]_page_actions_075w~g2.js")
R.m(10054)
module.exports=R.m(10054).exports
