ALTER TABLE "SiteContent"
ADD COLUMN "footerDescription" TEXT NOT NULL DEFAULT 'Keyfiyyetli ehtiyat hisseleri, rahat sifaris ve suretli destek bir yerde.',
ADD COLUMN "footerHighlightLabel" TEXT NOT NULL DEFAULT 'Destek xidmeti',
ADD COLUMN "footerHighlightValue" TEXT NOT NULL DEFAULT '24/7',
ADD COLUMN "footerWorkHoursLabel" TEXT NOT NULL DEFAULT 'Is gunleri',
ADD COLUMN "footerWorkHoursValue" TEXT NOT NULL DEFAULT 'Be. - Ce. / 09:00 - 18:00',
ADD COLUMN "footerPhoneLabel" TEXT NOT NULL DEFAULT 'Elaqe nomresi',
ADD COLUMN "footerPhoneValue" TEXT NOT NULL DEFAULT '+994 55 738 00 13',
ADD COLUMN "footerEmailLabel" TEXT NOT NULL DEFAULT 'E-poct',
ADD COLUMN "footerEmailValue" TEXT NOT NULL DEFAULT 'info@avtopro.az',
ADD COLUMN "footerSocialLabel" TEXT NOT NULL DEFAULT 'Bizi izleyin',
ADD COLUMN "footerFacebookUrl" TEXT NOT NULL DEFAULT 'https://facebook.com',
ADD COLUMN "footerInstagramUrl" TEXT NOT NULL DEFAULT 'https://instagram.com',
ADD COLUMN "footerLinkedinUrl" TEXT NOT NULL DEFAULT 'https://linkedin.com',
ADD COLUMN "footerTiktokUrl" TEXT NOT NULL DEFAULT 'https://tiktok.com',
ADD COLUMN "footerCopyright" TEXT NOT NULL DEFAULT 'Detalcenter.az 2026, Butun huquqlar qorunur.',
ADD COLUMN "footerPrivacyLabel" TEXT NOT NULL DEFAULT 'Mexfilik siyaseti',
ADD COLUMN "footerTermsLabel" TEXT NOT NULL DEFAULT 'Sertler ve qaydalar',
ADD COLUMN "footerAboutLabel" TEXT NOT NULL DEFAULT 'Haqqimizda',
ADD COLUMN "footerFaqLabel" TEXT NOT NULL DEFAULT 'Tez-tez verilen suallar';
