var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/seller/[id]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__07c0~y1._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0-31khf.js")
R.c("server/chunks/ssr/[root-of-the-server]__0eh9ux8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_06hehg4._.js")
R.c("server/chunks/ssr/_0jytjc.._.js")
R.c("server/chunks/ssr/_0on~~aa._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_0wkf-8i._.js")
R.c("server/chunks/ssr/_next-internal_server_app_seller_[id]_page_actions_0lhkt4d.js")
R.m(56340)
module.exports=R.m(56340).exports
