var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/catalog/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0wawovv._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0um3um4.js")
R.c("server/chunks/ssr/[root-of-the-server]__0eh9ux8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_06hehg4._.js")
R.c("server/chunks/ssr/_0jytjc.._.js")
R.c("server/chunks/ssr/_0on~~aa._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_catalog_page_actions_0hei~r..js")
R.m(86544)
module.exports=R.m(86544).exports
