var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/product/[id]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0deibh8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0c~wvze.js")
R.c("server/chunks/ssr/[root-of-the-server]__0eh9ux8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_06hehg4._.js")
R.c("server/chunks/ssr/_0jytjc.._.js")
R.c("server/chunks/ssr/_0on~~aa._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_044~xc2._.js")
R.c("server/chunks/ssr/app_product_[id]_loading_jsx_0__y7gl._.js")
R.c("server/chunks/ssr/_next-internal_server_app_product_[id]_page_actions_0tcda~o.js")
R.m(56637)
module.exports=R.m(56637).exports
