ALTER TABLE "Product" ADD COLUMN "brand" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Product" ADD COLUMN "model" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Product" ADD COLUMN "year" INTEGER;
ALTER TABLE "Product" ADD COLUMN "engine" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Product" ADD COLUMN "vinCodes" TEXT NOT NULL DEFAULT '[]';
